# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllosaurusAvarus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AllosaurusAvarus
pod 'RAMAnimatedTabBarController', "~> 2.0.13"
pod 'FlickToDismiss', '~> 0.9'
pod 'GTProgressBar'
pod 'BrickKit'
pod 'Charts'
end
